apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-updater-demo
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: image-updater-demo
  template:
    metadata:
      labels:
        app: image-updater-demo
    spec:
      containers:
        - name: image-updater-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.targetPort } }
