apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo=038462753889.dkr.ecr.us-east-1.amazonaws.com/image-updater-demo
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/demo.force-update: "true"
    argocd-image-updater.argoproj.io/demo.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/dnyaneshwar-gitte/argocd-image-updater-assessment.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true